<a href="https://colab.research.google.com/github/jakekrafczyk/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/Copy_of_LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The first and visible layer of the network. Equivalent to x in an algebraic function. 
### Hidden Layer: A middle layer in the network. This is where the weights are calculated and is equivalent to W in an algebraic function.
### Output Layer: The last layer in the network. This layer often includes a sigmoid function that simplifies the output from the hidden layers. Equivalent to y in an algebraic function.
### Neuron: A neuron is a cell in our brain that inputs and outputs the electrical signals in our brain. Neural networks are modeled after these.
### Weight: The weight is a variable that determines how much importance we assign to a given input. 
### Activation Function: The sigmoid function mentioned above is an activation function. It is a transformation function that takes the hidden layer output and makes it more understandable for the purposes of our model.
### Node Map: Node maps are a visualization of how input layers, hidden layers, and output layers are structured within the neural network.
### Perceptron: The perceptron is the simplest neural network. It is just an input layer, a hidden layer, and an output layer.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here


## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
##### Your Code Here #####
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [0]:
inputs = np.array(df.drop(columns='y'))
print(inputs)
outputs = np.array(df.y)
outputs = outputs.reshape(-1,1)
outputs


[[0 0]
 [1 0]
 [0 1]
 [1 1]]


array([[1],
       [1],
       [1],
       [0]])

In [0]:
np.random.seed(0)

weights = np.random.random((2,1))
print(weights)

weighted_sum = np.dot(inputs, weights)
print(weighted_sum)

activated_output = sigmoid(weighted_sum)
print(activated_output)

[[0.5488135 ]
 [0.71518937]]
[[0.        ]
 [0.5488135 ]
 [0.71518937]
 [1.26400287]]
[[0.5       ]
 [0.63386027]
 [0.6715468 ]
 [0.77971441]]


In [0]:
error = outputs - activated_output
error

array([[ 0.5       ],
       [ 0.36613973],
       [ 0.3284532 ],
       [-0.77971441]])

In [0]:
adjustments = error * sigmoid_derivative(weighted_sum)

weights += np.dot(inputs.T, adjustments)
weights

array([[0.49986411],
       [0.65371321]])

In [0]:
print(outputs, activated_output)

[[1]
 [1]
 [1]
 [0]] [[0.5       ]
 [0.63386027]
 [0.6715468 ]
 [0.77971441]]


In [0]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-3.19189120e-16]
 [ 1.52655666e-16]]
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [0]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = np.array(diabetes.drop(columns='Outcome'))
scaler = MinMaxScaler()
scaler.fit(X)
scaler.transform(X)


array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [0]:
##### Update this Class #####

# uses sigmoid function
# need to figure out how to handle the bias value
# for the training loop: should use the training loop from class vv
'''
# Steps we've already done: 
# 1. Randomly Initialized Weights already. Those are in memory as `weights`
# 2. We've already got input data & correct_outputs


# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivate(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)
'''

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = np.random.random((2,1))

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights)
            
            # Activate!
            activated_output = sigmoid(weighted_sum)
            
            # Cac error
            error = y - activated_output
            
            adjustments = error * sigmoid_derivative(weighted_sum)
            
            # Update the Weights
            weights += np.dot(X.T, adjustments)


    def predict(self, X):
    """Return class label after unit step"""
        
        return None

IndentationError: ignored

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?