<a href="https://colab.research.google.com/github/jakekrafczyk/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module2-backpropagation/Copy_of_LS_DS_432_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Using TensorFlow Keras, Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn.

This is your "Hello World!" of TensorFlow.

### Example TensorFlow Starter Code

```python 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

results = model.fit(X,y, epochs=100)

```

### Additional Written Tasks:
1. Investigate the various [loss functions](https://www.tensorflow.org/api_docs/python/tf/keras/losses). Which is best suited for the task at hand (predicting 1 / 0) and why? 
2. What is the difference between a loss function and a metric? Why might we need both in Keras? 
3. Investigate the various [optimizers](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers). Stochastic Gradient Descent (`sgd`) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as `adam` have to offer? 

In [0]:
##### Your Code Here #####
import pandas as pd
import numpy as np
data = { 'x1': [0,0,1,0,1,1,0],
         'x2': [0,1,0,1,0,1,0],
         'x3': [1,1,1,0,0,1,0],
         'y':  [0,1,1,1,1,0,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
X = df[['x1', 'x2','x3']].values
y = df['y'].values
print(X,y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]] [0 1 1 1 1 0 0]


In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
 
model = Sequential([
    Dense(3, activation='sigmoid', input_dim=3),
    Dense(1, activation='sigmoid')
])
 
model.compile(optimizer='sgd', loss='KLD', metrics=['acc'])
 
results = model.fit(X,y, epochs=100)
print(results)
# sgd, binary_cross = .429
# adam, binary_cross = .429
# adam, hinge = .285
# adam, huber = .429
# adam, KLD = .571

# sgd = stochastic gradient descent
# momentum = how much an outlier slows down the descent
# acceleration = adding this helps keep the momentum from overshooting
# adam is efficient and accurate. combines momentum techniques with adadelta

In [0]:
scores = model.evaluate(X, y)
print(f"{model.metrics_names[1]}: {scores[1]*100}")

1/1 [==============================] - 0s 1ms/step - loss: 0.3034 - acc: 0.5714
acc: 57.14285969734192


### Build a Tensor Keras Perceptron

Try to match the architecture we used on Monday - inputs nodes and one output node. Apply this architecture to the XOR-ish dataset above. 

After fitting your model answer these questions: 

Are you able to achieve the same results as a bigger architecture from the first part of the assignment? Why is this disparity the case? What properties of the XOR dataset would cause this disparity? 

Now extrapolate this behavior on a much larger dataset in terms of features. What kind of architecture decisions could we make to avoid the problems the XOR dataset presents at scale? 

*Note:* The bias term is baked in by default in the Dense layer.

In [0]:
### Compare 
model = Sequential()
model.add(Dense(1,input_dim=3, activation='sigmoid'))
model.compile(loss='KLD', optimizer='adam', metrics=['accuracy'])
model.fit(X,y, epochs=25)

Epoch 1/25
1/1 [==============================] - 0s 1ms/step - loss: 0.2455 - accuracy: 0.5714
Epoch 2/25
1/1 [==============================] - 0s 1ms/step - loss: 0.2451 - accuracy: 0.4286
Epoch 3/25
1/1 [==============================] - 0s 2ms/step - loss: 0.2446 - accuracy: 0.4286
Epoch 4/25
1/1 [==============================] - 0s 1ms/step - loss: 0.2442 - accuracy: 0.4286
Epoch 5/25
1/1 [==============================] - 0s 2ms/step - loss: 0.2437 - accuracy: 0.4286
Epoch 6/25
1/1 [==============================] - 0s 1ms/step - loss: 0.2433 - accuracy: 0.4286
Epoch 7/25
1/1 [==============================] - 0s 1ms/step - loss: 0.2429 - accuracy: 0.4286
Epoch 8/25
1/1 [==============================] - 0s 2ms/step - loss: 0.2424 - accuracy: 0.4286
Epoch 9/25
1/1 [==============================] - 0s 1ms/step - loss: 0.2420 - accuracy: 0.4286
Epoch 10/25
1/1 [==============================] - 0s 2ms/step - loss: 0.2415 - accuracy: 0.4286
Epoch 11/25
1/1 [======================

In [0]:
scores = model.evaluate(X, y)
print(f"{model.metrics_names[1]}: {scores[1]*100}")

1/1 [==============================] - 0s 1ms/step - loss: 0.2346 - accuracy: 0.4286
accuracy: 42.85714328289032


## Try building/training a more complex MLP on a bigger dataset.

Use TensorFlow Keras & the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the canonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the Internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [0]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [0]:
# input image dimensions
img_rows, img_cols = 28, 28

In [0]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [0]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simplify the problem for now: Zero or all else.

In [0]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [0]:
# A Nice Binary target for ya to work with
y_train.shape

(60000,)

### Estimating Your `net

In [0]:
x_test.shape

(10000, 784)

In [0]:
##### Your Code Here #####
model = Sequential([
    Dense(32, activation='relu'),
    Dense(2, activation='relu')
])
 
model.compile(optimizer='adam', loss='KLD', metrics=['acc'])
 
results = model.fit(x_train,y_train, epochs=30)
print(results)

Epoch 1/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0056 - acc: 0.7983
Epoch 2/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.5561e-06 - acc: 0.6693
Epoch 3/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-06 - acc: 0.8415
Epoch 4/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-06 - acc: 0.8411
Epoch 5/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-06 - acc: 0.8407
Epoch 6/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-06 - acc: 0.8401
Epoch 7/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-06 - acc: 0.8395
Epoch 8/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-06 - acc: 0.8387
Epoch 9/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-06 - acc: 0.8375
Epoch 10/30
1875/1875 [==============================] - 2s 1ms/step - loss: -2.9054e-0

In [0]:
scores = model.evaluate(x_test, y_test)
print(f"{model.metrics_names[1]}: {scores[1]*100}")

313/313 [==============================] - 0s 971us/step - loss: 1.5796 - acc: 0.9020
acc: 90.20000100135803


## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?